### ISSUE TITLE
Guest Sanity: Boundary tests failing

### ISSUE THREAD

**Issue by rquander** [open-power-host-os/tests#10]
**Guest Sanity: Boundary tests failing**

**Reason for Failure:**
Avocado-vt bug to login to the guest when multiple interfaces added to the guest

**Testcases affected:**
163-guest_sanity.boundary.network_max.spaprvlan.qemu.qcow2.scsi.smp2.spapr-vlan.Fedora.23.ppc64le.io-github-autotest-qemu.unattended_install.import.import.default_install.aio_native
165-guest_sanity.boundary.network_max.virtionet.qemu.qcow2.scsi.smp2.virtio_net.Fedora.23.ppc64le.io-github-autotest-qemu.unattended_install.import.import.default_install.aio_native

**Resolution action:**
Working with the Avocado-vt community to fix this issue.

**Workaround:**
Skip boundary tests by commenting them out in the test config file guest_sanity.cfg

**Comment by rquander** [comment]
Working this issue via [avocado-vt Issue #617](https://github.com/avocado-framework/avocado-vt/issues/617) .

**Comment by rquander** [comment]
More work is needed with avocado-vt team to determine the best resolution for this issue.  In the interim, the failing tests will be commented out by default until this issue is resolved.

**Comment by sathnaga** [comment]
@rquander I have got my fix to this issue merged today https://github.com/avocado-framework/avocado-vt/commit/36a0ab1fe40ae3694ae6fdf5fc525b12a0c30861, This test case will be working from now, you can choose to revert the PR for removing this test.

**Comment by rquander** [comment]
@sathnaga Thanks for the update!  I reverted this change in the above referenced PR #42 .  Closing this issue now.
