### ISSUE TITLE
Add Centos 7.2 guest support

### ISSUE THREAD

**Issue by sathnaga** [open-power-host-os/tests#13]
Centos 7.2 guest support

**Comment by rquander** [comment]
CentOS VM installation patch merged upstream in the avocado-vt repository via [Pull Request #707](https://github.com/avocado-framework/avocado-vt/pull/707).
@sathnaga is working on a Host OS Test Suite patch to enable support of this VM OS after validation of the current sanity test sets is completed against CentOS VM.

**Comment by sathnaga** [comment]
Pull request got accepted in upstream, Working on to enable it in test suite
