### ISSUE TITLE
Tests results are not getting populated in the directory mention in the test command line.

### ISSUE THREAD

**Issue by vaishnavibhat** [open-power-host-os/tests#137]
I ran the below command line after creating a directory 'slate'
python avocado-setup.py --run-suite host_io_network_fvt --input-file input.txt --output-dir slate

Seeing issues on running this:
1) Results are not populated in the directory slate but under /root/avocado-fvt-wrapper/results/
2) Summary of the results is like below even if tests are run
15:32:20 INFO    : Summary of test results can be found below:
TestSuite                                                                   TestRun    Summary

host_io_network_fvt_pci_hotplug_pci_hotplug                                 Not_Run    Unable to find job log file

host_io_network_fvt_driver_bind_test_driver_bind_test                       Not_Run    Unable to find job log file

**Comment by narasimhan-v** [comment]
bad commit: https://github.com/open-power-host-os/tests/commit/6a61f1856778384f5f1c7bcabf4e90993f28b59e#diff-e22672c7195a318617e9714b76f27395L623
Sending a fix for it.

**Comment by narasimhan-v** [comment]
Fixed:
https://github.com/open-power-host-os/tests/pull/138

**Comment by sathnaga** [comment]
Merged
