### ISSUE TITLE
Exercise XICS and XIVE interrupt models and dual mode

### ISSUE THREAD

**Issue by mopsfelder** [open-power-host-os/tests#191]

**Comment by sathnaga** [comment]
these scenario's are covered here, https://github.com/open-power-host-os/tests/blob/master/config/tests/guest/libvirt/upstream.cfg#L176

**Comment by sathnaga** [comment]
Closing as per previous comment..

**Comment by sathnaga** [comment]
Thanks @mopsfelder :-)
