### ISSUE TITLE
Investigate and integrate 4Q2016 Distro OS tests into Host OS Test Suite

### ISSUE THREAD

**Issue by rquander** [open-power-host-os/tests#22]
Investigate potentially integrating applicable Distro OS tests into Host OS Test Suite.

**Comment by rquander** [comment]
These automated tests are already being integrated into the Avocado test framework in various folders of the [avocado-misc-tests](https://github.com/avocado-framework/avocado-misc-tests) repository.

This investigation will focus on determining which subset of tests should be in the short and full overall sanity test suites and which may be pulled into separate optional OS_sanity_test and OS_all_test buckets in case users wish to dive deeper into OS testing.

**Comment by sathnaga** [comment]
@rquander avocado-misc-test repo location has been changed in upstream, have sent the pull https://github.com/open-power-host-os/tests/pull/26 to change in our repo.

Use this repo here after:https://github.com/avocado-framework-tests/avocado-misc-tests

**Comment by rquander** [comment]
Update:

I updated 

1. the avocado-misc-tests link per sathnaga's comment above.  
2. As the Disro OS FVT team submits more tests upstream to the avocado-misc-tests repository, each test will be reviewed to be placed in the default short/full sanity suites and/or in a separate DistroOS deep dive test suite.
3. Near-future new tests will be added to the respective suites in late October 2016 and December 2016 when this Issues will be closed.
4. New issues will be opened for future tests (2017 & beyond) to be reviewed and added to test suites. I will open issues for groups of tests and not each individual test (unless it is a very high priority test that does not line 

up with other group test schedules).

**Comment by rquander** [comment]
There will be no additional Distro OS tests added to the Host OS Test Suite in 4Q2016.  A new Issue will be opened for 1st Quarter 2017 to continue reviewing and integrating potential new tests within that time frame.
