### ISSUE TITLE
Python errors with avocado-setup.py

### ISSUE THREAD

**Issue by manvanthar** [open-power-host-os/tests#238]
Python errors with avocado-setup.py

#python avocado-setup.py --run-suite host_io_roce_fvt --output-dir roce_logs --input-file input_IB.txt
1:45:23 INFO    : Check for environment
Traceback (most recent call last):
  File "avocado-setup.py", line 640, in <module>
    if (args.bootstrap or need_bootstrap(args.enable_kvm)):
  File "avocado-setup.py", line 192, in need_bootstrap
    repo_name = repo.split('/')[-1].split('.')[0]
AttributeError: 'tuple' object has no attribute 'split'

**Comment by PraveenPenguin** [comment]
@manvanthar as wrapper env conf is empty refer this , 

https://github.com/open-power-host-os/tests/blob/master/config/wrapper/env.conf#L6-L7

please populate with repo details it will work

**Comment by PraveenPenguin** [comment]
@manvanthar my Bad , this PR https://github.com/open-power-host-os/tests/pull/239 will solve the issue
