### ISSUE TITLE
Automate posting Host OS build test results

### ISSUE THREAD

**Issue by rquander** [open-power-host-os/tests#28]
<cde:info> Mirrored with LTC bug https://bugzilla.linux.ibm.com/show_bug.cgi?id=170761 </cde:info>

There is an [Issue #1 in the open-power-host-os.github.io repo](https://github.com/open-power-host-os/open-power-host-os.github.io/issues/1) tracking the overall plan to publish and reference the test results for the Host OS weekly builds in Github.  The plan is copied below for reference.

This issue is for tracking the additional CI automation necessary to gather the test results files and post them externally to the correct repository.

Overall Plan:
1) Create static folders in the [github.io repo ](https://github.com/open-power-host-os/open-power-host-os.github.io) for storage of weekly test results. "Weekly_Build_Test_Results" high level folder and "Latest_Test_Results" sub-folder.
2) Post the most recent test results HTML and companion files for each weekly build into a subfolder of the static "Weekly_Build_Test_Results" folder with a date/time stamp associated with the build date.
3) Post the most recent test results files also to the "Latest_Test_Results" static sub-folder (overwrite previous results).
4) Add text and static links referencing the latest test results from the "Latest_Test_Results" static sub-folder in the [github.io README file](https://github.com/open-power-host-os/open-power-host-os.github.io/blob/master/README.md).

**Comment by sathnaga** [comment]
@rquander @rmatinata-ibm @olavphibm @maurorodrigues @bssrikanth I am not sure, how much relevance weekly build results to community, we can discuss in detail internally, results for every release say 1.0, 1.5 make sense?

**Comment by rquander** [comment]
I agree that this requires additional discussion and will likely also require more code to implement properly.  I am shifting this feature to the December 31st delivery milestone.

**Comment by rquander** [comment]
After further discussion, we believe full detailed test results for each build will not be used by most and is likely wasted effort.

Instead, a more concise, brief test results overview should be posted for each updated build that includes info such as:
1) Which specific test suites were run (host_sanity, guest_sanity, etc.).
2) How long the entire test run took to complete.
3) The resulting percent pass/fail.

This info will likely be included in the [Weekly Build Issues of the Host OS builds repository](https://github.com/open-power-host-os/builds/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3A%22Weekly%20Build%22).

After implementing the above strategy, new Issues will be opened to track additional enhancements to this feature (more detailed failure info if failures occur, etc.).

**Comment by olavphibm** [comment]
I am currently working on automating the announcement of release notes and creating pages for them in https://github.com/open-power-host-os/open-power-host-os.github.io (see open-power-host-os/builds#43). Maybe that'll be a good place to publish the test results.

**Comment by olavphibm** [comment]
@rquander @sathnaga 
We now have automated release notes creation in https://open-power-host-os.github.io/
If you decide to post the test results there too, we can work together on the format to display the release notes together with tests.

**Comment by rquander** [comment]
The method to automate posting test results is clear, but we are still investigating which specific conditions must be met before automatic test results are posted.  Since internal testing is performed on builds that may not be released to GitHub, we must avoid posting test results for a build that does not exist from a GitHub user's standpoint.  Internal Continuous Integration jobs will need adjustment and testing before automatic test results posting is enabled.

**Comment by rquander** [comment]
@mopsfelder @olavphibm @sathnaga 
We need to discuss this item further in the new year to determine the best way to combine the continuous integration test results with the build release notes.  I believe we can integrate building and testing into a more tightly integrated job and create a single PR for release notes when necessary.

**Comment by olavphibm** [comment]
I think integrating test results into the release notes would be ideal. Let us wait for the new year to discuss this then.

**Comment by cdeadmin** [comment]
------- Comment From rquander@us.ibm.com 2018-08-23 15:07:49 EDT-------
Assigning to Murilo.
