### ISSUE TITLE
Investigate potentially integrating automated PowerKVM System Tests into Host OS Test Suite

### ISSUE THREAD

**Issue by rquander** [open-power-host-os/tests#29]
System test teams tend to run longer and more complex tests, some of which may be fully automated.  I will investigate the automated tests further to determine if any of them could or should be integrated into the Host OS Test Suite either as part of the default sanity suite or as an optional more detailed suite.

<cde:info> Mirrored with LTC bug #159687 </cde:info>

**Comment by rquander** [comment]
Updated the milestone date to TBD since this is an on-going investigation.

**Comment by rquander** [comment]
Currently the PowerKVM System Tests are more complex than is prudent to try to integrate into an overall sanity test for new installations.  As new/adjusted System Tests are added to the suite, this investigation will continue to see if it makes sense to integrate a subset of the tests into the current sanity test suites.

**Comment by rquander** [comment]
Closing this issue.  After further investigation, I've determined that the systems tests are not unique enough to warrant including them into this quite.  The current suite covers more basic functionality, which is the overall goal of this suite.

**Comment by cdeadmin** [comment]
------- Comment From rquander@us.ibm.com 2018-06-20 13:26:22 EDT-------
Closed per linked GitHub issue comments.
