### ISSUE TITLE
Test Debian-based HostOS Host

### ISSUE THREAD

**Issue by rquander** [open-power-host-os/tests#30]
Investigate running Host OS tests against a Debian-based Host OS system.

This will remain an investigation item until I discover if/when Host OS build will install on Debian (prerequisite for test support).

<cde:info> Mirrored with LTC bug #157748 </cde:info>

**Comment by laggarcia** [comment]
Shouldn't we separate host tests from guest tests? I mean, we can test Debian as a guest on top of current HostOS anyway, such as issue 18 is for Ubuntu. On the other hand, when we start supporting any new host base, we might need to repeat all tests, including a variety of tests on different types of guests, with this new host base.

**Comment by rquander** [comment]
@laggarcia Since this was originally a general investigation issue and not an issue to track testing, combining host and guest was not a problem.  I think now is a good time to adjust this story to something more active though, so I will change this one and create a new one to separate guest and host testing for Debian.  Thanks for your input!

**Comment by cdeadmin** [comment]
------- Comment From lagarcia@br.ibm.com 2017-11-12 20:30:41 EDT-------
We decided not to pursue this at this time. We will wait until a real requirement appears.
