### ISSUE TITLE
Create strategy for users to run Host OS version-specific test suites

### ISSUE THREAD

**Issue by rquander** [open-power-host-os/tests#48]
As new versions of Host OS are released, certain individual test scripts/variants within the test suite may not be compatible on all previously released versions (only support newer features, etc.).  A strategy needs to be put into place to clearly indicate which pre-configured test suite can be run on which Host OS version.

**Option 1:**  Tag the test suite repository code with a new release that matches the Host OS release where it is compatible.
- Pro: It's quick and easy to do.
- Con: New test script/variant releases may still be backwards compatible but would not be automatically included in previous tagged releases because of timing. 

**Option 2:**  Create Host OS version-specific test suite configuration files that include the test scripts/variants that are supported on that version.
- Pro: This allows for any new test script/variant to be added to every release config file that it is compatible with, always providing the user with maximum available coverage for each relevant release.
- Con: Instead of having a single release for each Host OS version, the repository will have 3-4 new test suite config files (short and full sanity suites for host and guest testing) for each Host OS version (potentially multiple Pull Requests to review and commit).  More time is necessary to verify which new test scripts/variants are compatible with which releases.

**Option 3:**  Branch the test suite into separate branches based on the Host OS release where it is compatible.
- Pro: Users can choose which branch to download based on which Host OS version they plan to install (just match the version numbers). New test scripts/variants can be committed to multiple branches based on which Host OS version they are compatible with, keeping all branches updated and properly tracked with the latest coverage.  The default master branch will always be the most recent and be compatible with the most recent Host OS version available.
- Con: Set up and usage of multiple branches is more complex than the other options though it may be the most organized solution to the problem of potential missing coverage in previous versions. 

**At present I'm leaning heavily towards Option 3.**

**Comment by fabianorosas** [comment]
Just as an insight into this, what we currently do with the versions + builds repositories is equivalent to your "Option 1", keeping matching tags in each git repo. To build previous HostOS versions, we just checkout both tags and are good to go.

About the 'con' you mention for option 1, why do we need to add new tests to already tested versions? Wouldn't that go against the overall philosophy of HostOS, i.e. working with the most up-to-date development snapshots?

**Comment by rquander** [comment]
@fabianorosas To answer your question, my assumption is that if users are downloading and installing versions of Host OS that are NOT the latest then they will want a matching test suite that includes as much test coverage as we can provide for that Host OS version.  Various contributors are consistently creating new test scripts both for new features and to enhance the regressions bucket for established features.  The goal is to continually add coverage to all relevant test suites as new tests of either type (new feature or regression) are submitted.

**Comment by rquander** [comment]
After further consideration, I've decided to go with Option 1 since it's less likely that users will focus very much on older Host OS releases.  I've already tagged v1.x (for Host OS 1.0 & 1.5) and v2.0 Releases, so I'll continue to tag new releases as new Host OS versions are published.
