### ISSUE TITLE
Add test case to validate systemtap

### ISSUE THREAD

**Issue by mopsfelder** [open-power-host-os/tests#49]
Systemtap needs to be on pair with kernel releases, e.g. kernel 4.10 requires systemtap >= 3.1.  Adding a test case to validate systemtap will let us know when it stops of functioning with newer kernels.

The test case can execute

```stap -v -e 'probe vfs.read {printf("read performed\n"); exit()}'```

and verify its return code.  This command was obtained from https://sourceware.org/systemtap/SystemTap_Beginners_Guide/using-systemtap.html#testing

**Comment by rquander** [comment]
@mopsfelder Let's discuss this further.  I need to understand if there are any additional packages that need checking when the Host OS kernel is updated and also if this should be an FVT test or an earlier build verification test to ensure general minimum package cooperation when HostOS is updated.

Thanks for alerting me to this.

**Comment by rquander** [comment]
[@poojabs7](https://github.com/poojabs7) submitted [Pull Request #353 in the avocado-misc-tests repository](https://github.com/avocado-framework-tests/avocado-misc-tests/pull/353) to add a systemtap.py test suite.  Once that tests is approved and integrated, I can add it to the host test suite here.

**Comment by rquander** [comment]
Merged on May 12th with [Pull Request #486 in the avocado-misc-tests repository](https://github.com/avocado-framework-tests/avocado-misc-tests/pull/486).
