### ISSUE TITLE
Sprint 1: test bz: [feat] qemu fails to start with compat mode

### ISSUE THREAD

**Issue by bssrikanth** [open-power-host-os/tests#59]
This is test bz to track the testcases development for below new feature targeted for sprint 1:
> 156273 qemu fails to start with compat mode

@sathnaga will be test owner.

@sathnaga please update with the testcases meant for testing this new feature.

<cde:info> Mirrored with LTC bug #158306 </cde:info>

**Comment by bssrikanth** [comment]
This is a bugzilla turned into feature request. @sathnaga has already tested the fix given as part of this feature with nightly build. But we would retest with release branch before closing this out.

**Comment by cdeadmin** [comment]
------- Comment From bssrikanth@in.ibm.com 2017-09-27 05:23:43 EDT-------
Closing as per previous comment
