### ISSUE TITLE
Guest Sanity: Hotplug tests failing

### ISSUE THREAD

**Issue by sathnaga** [open-power-host-os/tests#6]
**Guest Sanity: Hotplug tests failing**

**Reason for Failure:**
Failures due to ppc64-diag and servicelog package missing in default Fedora23 iso

**Testcases affected:**
087-guest_sanity.hotplug.disk.qemu.qcow2.scsi.smp2.spapr-vlan.Fedora.23.ppc64le.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.host_block_vm_id
089-guest_sanity.hotplug.disk.qemu.qcow2.scsi.smp2.spapr-vlan.Fedora.23.ppc64le.io-github-autotest-libvirt.virsh.attach_detach_disk.detach_disk.normal_test.host_block_vm_id
091-guest_sanity.hotplug.memory.qemu.qcow2.scsi.smp2.spapr-vlan.Fedora.23.ppc64le.io-github-autotest-libvirt.libvirt_mem.positive_test.hot_plug

**Resolution action:**
Raised a recommendation for Fedora to ship/have those packages by default.

**Workaround:**
Install ppc64-diag manually after the installation of guest and then run only these tests with filter
--only-filter "guest_sanity.hotplug"

**Comment by rquander** [comment]
If the prerequisite tools cannot be added to the default Fedora23 ISO, we'll need to resolve this issue via prereq documentation (Issue #14 ) and possibly automatic prere checking (Issue #15 ).

**Comment by sathnaga** [comment]
@rquander right now working on a patch for addressing guest dependancies for both stress and hotplug testcases, ll send a pull request soon

**Comment by sathnaga** [comment]
Fixed by install dependancies(guest_install):
TESTS      : 3
 (1/3) guest_install.qemu.qcow2.scsi.smp2.spapr-vlan.Fedora.24.ppc64le.io-github-autotest-qemu.unattended_install.cdrom.http_ks.default_install.aio_native:  PASS (474.36 s)
 (2/3) guest_dep_install.qemu.qcow2.scsi.smp2.spapr-vlan.Fedora.24.ppc64le.io-github-autotest-qemu.guest_test.isa_serial_operations:  PASS (34.86 s)
 (3/3) guest_remove.qemu.qcow2.scsi.smp2.spapr-vlan.Fedora.24.ppc64le.io-github-autotest-libvirt.remove_guest.without_disk:  PASS (9.69 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
TESTS TIME : 518.90 s

-----

 guest_sanity.hotplug.disk.qemu.qcow2.scsi.smp2.spapr-vlan.Fedora.24.ppc64le.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.host_block_vm_id:  PASS (71.67 s)
guest_sanity.hotplug.disk.qemu.qcow2.scsi.smp2.spapr-vlan.Fedora.24.ppc64le.io-github-autotest-libvirt.virsh.attach_detach_disk.detach_disk.normal_test.host_block_vm_id:  PASS (74.86 s)
guest_sanity.hotplug.memory.qemu.qcow2.scsi.smp2.spapr-vlan.Fedora.24.ppc64le.io-github-autotest-libvirt.libvirt_mem.positive_test.hot_plug:  PASS (69.73 s)
