### ISSUE TITLE
Sprint 1: test bz: [feat] Virtualization support for RCU stall detector

### ISSUE THREAD

**Issue by bssrikanth** [open-power-host-os/tests#61]
This is test bz to track the testcases development for below new feature targeted for sprint 1:
149893 [Feature] Virtualization support for RCU stall detector

Santwana will be test owner.

Santwana please update with the testcases meant for testing this new feature.

<cde:info> Mirrored with LTC bug #158311 </cde:info>

**Comment by bssrikanth** [comment]
This feature was a bug reported in bz145818. Minimum test scenario to cover would be:

1. Hot-plug an multifunction adapter to guest.
2. Suspend the guest.
3. Resume the guest. There should be no Call Traces

**Comment by cdeadmin** [comment]
------- Comment From bssrikanth@in.ibm.com 2017-09-25 05:53:15 EDT-------
Update: tested this feature. The issue still existing.. I have reopened the dev feat bugzilla

**Comment by cdeadmin** [comment]
------- Comment From bssrikanth@in.ibm.com 2017-09-27 05:22:05 EDT-------
This feature is tested. Marking it as 'Tested'
