### ISSUE TITLE
sprint 2: test bz: Memory hot unplug support in QEMU, libvirt

### ISSUE THREAD

**Issue by bssrikanth** [open-power-host-os/tests#70]
This is test tracker for dev feat : 146286 and 146285..
Memory hot unplug support in QEMU and libvirt.

@MalleshKoti would be owning this testing. He will be populating the testcases here for review.

<cde:info> Mirrored with LTC bug #159393 </cde:info>

**Comment by cdeadmin** [comment]
------- Comment From bharata.rao@in.ibm.com 2017-10-06 08:25:31 EDT-------
Hotplug - reboot - unplug
Hotplug - reboot - migrate - unplug
Hotplug - migrate - reboot - unplug
Coldplug - reboot - unplug
Coldplug - reboot - migrate - unplug
Coldplug - migrate - unplug
Coldplug - migrate -reboot -unplug

**Comment by cdeadmin** [comment]
------- Comment From magadagi@in.ibm.com 2017-10-09 05:16:38 EDT-------
Thanks Bharata for the review.

Here is the revised list of test scenarios:

1. Hotplug a guest with max memory and hotunplug it.
2. Hotplug guest with 8G memory with single numa node and hotunplug
3. Hotplug guest with 8G memory with multiple numa node and hotunplug
4. Hotplug guest with memory till the last slot and hotunplug.
5. Try hotplugging memory with no numa node and hotunplug.
6. hotplug memory continuosly with single numa node and continuosly hotunplug the memory
7. Hotplug and hotunplug memory under stress running inside guest
8. Hotplug memory to the guest -&gt; migrate -&gt; hotunplug
9. 1st Hotplug memory to the guest -&gt; migrate -&gt; 2nd hotplug -&gt; 2nd hotunplug -&gt; reverse migrate -&gt; 1st hotunplug
10. 1st Hotplug memory to the guest -&gt; migrate -&gt; 2nd hotplug -&gt; reverse migrate -&gt; 2nd hotunplug -&gt; 1st hotunplug
11. boot guest with hugepages and hotplug guest with huge memory and hotunplug
12. Hotplug guest with memory, reboot the guest and hotunplug 
13. Hotplug guest with memory, reboot the guest, migrate and hotunplug
14. Hotplug guest with memory, migrate guest, reboot the guest and hotunplug
15. Coldplug guest with memory, reboot the guest and unplug
16. Coldplug guest with memory, reboot the guest, migrate and unplug
17. Coldplug guest with memory, migrate and unplug
18. Coldplug guest with memory, migrate, reboot the guest and unplug.

**Comment by cdeadmin** [comment]
------- Comment From bssrikanth@in.ibm.com 2017-10-23 03:13:08 EDT-------
This feature testing is spilling over to sprint 3 due to number of unresolved bugs which are targeted for sprint 3 now:
153431
142737
156105
159863
