### ISSUE TITLE
sprint 2: test bz: [bug] 64-bit MMIO accesses with PCI Passthrough of LSI SAS Adapter

### ISSUE THREAD

**Issue by sathnaga** [open-power-host-os/tests#73]
This is test bz to track the testcases development for below new feature targeted for sprint 2:

153079 Problem with 64-bit MMIO accesses with PCI Passthrough of LSI SAS Adapter

<cde:info> Mirrored with LTC bug #159732 </cde:info>

**Comment by sathnaga** [comment]
Capturing recreation details from bzs
```
0001:03:00.0 Serial Attached SCSI controller [0107]: LSI Logic / Symbios Logic SAS3008 PCI-Express Fusion-MPT SAS-3 [1000:0097] (rev 02)

- Boot thehost with 'modprobe.blacklist=mpt3sas'
- Switch to SMT off ( ppc64_cpu --smt=off )
- Detach the device in the host ( virsh nodedev-dettach pci_0001_03_00_0 )
- Start a CentOS 7.3 guest ( virsh start --console centosalt73 ) with 'modprobe.blacklist=mpt3sas' too
- Load/Unload the mpt3sas driver a few times (the 'fault_state' message usually occurs, but might take 1 or 2 reloads occasionally),  modprobe mpt3sas && sleep 2 && modprobe -r mpt3sas && sleep 2 (repeat)```

**Comment by cdeadmin** [comment]
------- Comment From prudmiry@in.ibm.com 2017-10-17 09:03:03 EDT-------
Hi,

I tested the above scenario on LSI/SAS adapter.

i followed the above steps and for 5th step 
--&gt; i did 100 times using following script
import os
import time
for x in xrange(1, 100):
    os.system('modprobe mpt3sas')
    time.sleep(2)
    os.system('modprobe -r mpt3sas')
    time.sleep(2)

i didn't see any fault message.

can i increase the count and test?

**Comment by cdeadmin** [comment]
------- Comment From iranna.ankad@in.ibm.com 2017-10-17 10:39:44 EDT-------
(In reply to comment #4)
&gt; Hi,
&gt; 
&gt; I tested the above scenario on LSI/SAS adapter.
&gt; 
&gt; i followed the above steps and for 5th step 
&gt; --&gt; i did 100 times using following script
&gt; import os
&gt; import time
&gt; for x in xrange(1, 100):
&gt;     os.system('modprobe mpt3sas')
&gt;     time.sleep(2)
&gt;     os.system('modprobe -r mpt3sas')
&gt;     time.sleep(2)
&gt; 
&gt; i didn't see any fault message.
&gt; 
&gt; can i increase the count and test?

I think 100 times is good enough. So..we can conclude the fix

**Comment by cdeadmin** [comment]
------- Comment From bssrikanth@in.ibm.com 2017-10-18 01:59:38 EDT-------
(In reply to comment #5)
&gt; (In reply to comment #4)
&gt; &gt; Hi,
&gt; &gt; 
&gt; &gt; I tested the above scenario on LSI/SAS adapter.
&gt; &gt; 
&gt; &gt; i followed the above steps and for 5th step 
&gt; &gt; --&gt; i did 100 times using following script
&gt; &gt; import os
&gt; &gt; import time
&gt; &gt; for x in xrange(1, 100):
&gt; &gt;     os.system('modprobe mpt3sas')
&gt; &gt;     time.sleep(2)
&gt; &gt;     os.system('modprobe -r mpt3sas')
&gt; &gt;     time.sleep(2)
&gt; &gt; 
&gt; &gt; i didn't see any fault message.
&gt; &gt; 
&gt; &gt; can i increase the count and test?
&gt; 
&gt; I think 100 times is good enough. So..we can conclude the fix

Yes I think
