### ISSUE TITLE
Host Sanity: Schedule-related tests failing

### ISSUE THREAD

**Issue by sathnaga** [open-power-host-os/tests#8]
**1.**

**Reason for Failure:**
Few tests are failing due to known test issues
'abort01', 'kill11', 'sched_rr_get_interval01', 'sched_rr_get_interval02', 'sched_rr_get_interval03', 'sched_setparam02', 'sched_setparam03', 'sched_getscheduler01', 'gf17'

**Testcases affected:**
3-avocado-misc-tests/generic/ltp.py:ltp.test

**Resolution action:**
Sched related tests needs to be skipped
Debug further for other few tests and add skip to the test framework permanently or fix it

**Workaround:**
None as of now

**Comment by rquander** [comment]
This bug has successfully been worked around via pull request #39 .  More investigation is necessary to determine the best way to fix the root cause (test case issue only on a subset of OS's) in the original test.

**Comment by rquander** [comment]
ltp.py test is no longer included in the host sanity test suite, so this is not longer an issue with the Host OS test suite.
